'''
In this file you can define the branch to be included in the flat ntuple.
You can find some basic quantities here, expand with more specific observables,
such as isolation etc...
'''
branches = [
    'run',
    'lumi',
    'event',
    'nvtx',
    'tau_reco_mass',
    'tau_reco_pt',
    'tau_reco_eta',
    'tau_reco_phi',
    'tau_reco_charge',
    'tau_reco_decaymode',
    'tau_reco_ip3d',
    'tau_reco_dxy',
    'tau_reco_pixel',
    'tau_reco_origAlgo',
    'tau_reco_algo',
    'tau_l1_pt',
    'tau_l1_eta',
    'tau_l1_phi',
    'tau_l1_charge',
    'tau_l1_iso',
    'jet_l1_pt',
    'jet_l1_eta',
    'jet_l1_phi',
    'jet_l1_charge',
    'tau_general_pt',
    'tau_general_eta',
    'tau_general_phi',
    'tau_general_charge',
#    'tau_com_pt',
#    'tau_com_eta',
#    'tau_com_phi',
#    'tau_com_charge',
#    'tau_com_pixel',
#    'tau_up_com_pt',
#    'tau_up_com_eta',
#    'tau_up_com_phi',
#    'tau_up_com_charge',
    'tau_hltPFdispltau_mass',
    'tau_hltPFdispltau_pt',
    'tau_hltPFdispltau_eta',
    'tau_hltPFdispltau_phi',
    'tau_hltPFdispltau_charge',
    'tau_hltPFdispltau_decaymode',
    'tau_hltPFdispltau_leadChargedCandPdgId',
    'tau_hltPFdispltau_leadChargedCandPt',
    'tau_hltPFdispltau_leadPFCandPdgId',
    'tau_hltPFdispltau_leadPFCandPt',
    'tau_hltPFdispltau_maxHCALPFClusterEt',
    'tau_hltPFdispltau_nChargedHad',
    'tau_hltPFdispltau_nGamma',
    'tau_hltPFdispltau_sumPtCharged',
    'tau_hltPFdispltau_sumPtNeutral',
    'tau_hltPFdispltau_dxy',
    'tau_hltPFdispltau_dxyerr',
    'tau_hltPFdispltau_ip3d',
    'tau_hltPFdispltau_ip3derr',
    'tau_hltPFdispltau_passChargedIso',
    'tau_hltPFdispltau_passRelChargedIso',
    'tau_hltPFdispltau_passAbsChargedIso',
    'tau_hltPFdispltau_isoval',
    'tau_hltPFdispltau_passFilters',
    'tau_gen_pt',
    'tau_gen_eta',
    'tau_gen_phi',
    'tau_gen_charge',
    'tau_gen_decaymode',
    'tau_gen_vis_mass',
    'tau_gen_vis_pt',
    'tau_gen_vis_eta',
    'tau_gen_vis_phi',
    'tau_gen_lxy',
    'tau_gen_dxy'
    'tau_gen_vx',
    'tau_gen_vy',
    'tau_gen_vz',
    'tau_gen_cosxy',
    'tau_gen_momct',
    'tau_gen_momct2d',
    'tau_gen_mom_mass',
    'jet_mass',
    'jet_pt',
    'jet_eta',
    'jet_phi',
    'jet_charge',
    'PV_x',
    'PV_y',
    'PV_z',
    'gen_ele_ndau',
    'gen_ele_pt',
    'gen_ele_eta',
    'gen_ele_phi',
    'gen_ele_charge',
    'gen_ele_lxy',
    'gen_ele_dxy',
    'gen_ele_vx',
    'gen_ele_vy',
    'gen_ele_vz',
    'gen_ele_cosxy',
    'gen_ele_mom_mass',
    'gen_ele_mom_pt',
    'gen_ele_mom_eta',
    'gen_ele_mom_phi',
    'gen_ele_momct2d',
    'gen_ele_vis_mass',
    'gen_ele_vis_pt',
    'gen_ele_vis_eta',
    'gen_ele_vis_phi',
    'l1_ele_pt',
    'l1_ele_eta',
    'l1_ele_phi',
    'l1_ele_charge',
    'hlt_ele_pt',
    'hlt_ele_eta',
    'hlt_ele_phi',
    'hlt_ele_charge',
]
